topic:
  name: boe

spring:
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
    producer:
        key.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
        schema.registry.url: http://localhost:8081
        properties:
          schema.registry.url: http://localhost:8081
    bootstrap-servers: localhost:9092
    template:
      default-topic: boe