version: '3.8'
services:

  redpanda:
    image: docker.vectorized.io/vectorized/redpanda:${REDPANDA_VERSION}
    restart: unless-stopped
    container_name: ${REDPANDA_CONTAINER_NAME}
    command:
     - redpanda start
     - --overprovisioned
     - --smp 1
     - --memory 1G
     - --reserve-memory 0M
     - --node-id 0
     - --check=false
     - --kafka-addr 0.0.0.0:${REDPANDA_PORT_KAFKA_INTERNAL}
     - --advertise-kafka-addr redpanda:${REDPANDA_PORT_KAFKA_INTERNAL}
     - --pandaproxy-addr 0.0.0.0:${REDPANDA_PORT_HTTP_INTERNAL}
     - --advertise-pandaproxy-addr redpanda:${REDPANDA_PORT_HTTP_INTERNAL}
     - --set redpanda.enable_transactions=true
     - --set redpanda.enable_idempotence=true
    ports:
     - "${REDPANDA_PORT_SCHEMA_EXTERNAL}:${REDPANDA_PORT_SCHEMA_INTERNAL}"          # Schema Registry port
     - "${REDPANDA_PORT_HTTP_EXTERNAL}:${REDPANDA_PORT_HTTP_INTERNAL}"              # HTTP Proxy port
     - "${REDPANDA_PORT_KAFKA_EXTERNAL}:${REDPANDA_PORT_KAFKA_INTERNAL}"            # Kafka API port
     - "${REDPANDA_PORT_PROMETHEUS_EXTERNAL}:${REDPANDA_PORT_PROMETHEUS_INTERNAL}"  #  Prometheus and HTTP admin port
     - "${REDPANDA_PORT_GRPC_EXTERNAL}:${REDPANDA_PORT_GRPC_INTERNAL}"              # internal RPC port
    volumes:
      - redpanda:/var/lib/redpanda/data
    healthcheck: {test: "curl -f localhost:${REDPANDA_PORT_PROMETHEUS_INTERNAL}/v1/status/ready", interval: 1s, start_period: 30s}
    profiles:
      - redpanda

  redpanda-console:
    image: docker.redpanda.com/vectorized/console:${REDPANDA_CONSOLE_VERSION}
    restart: unless-stopped
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:${REDPANDA_PORT_KAFKA_INTERNAL}"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:${REDPANDA_PORT_SCHEMA_INTERNAL}"]
        connect:
          enabled: true
          clusters:
            - name: datagen
              url: http://connect:${REDPANDA_PORT_CONNECT_INTERNAL}
    ports:
      - "${REDPANDA_CONSOLE_PORT_EXTERNAL}:${REDPANDA_CONSOLE_PORT_INTERNAL}"
    healthcheck: { test: "curl -f localhost:${REDPANDA_CONSOLE_PORT_INTERNAL}", interval: 1s, start_period: 30s }
    depends_on:
      redpanda:
        condition: service_healthy
    profiles:
      - redpanda

  connect:
    image: docker.cloudsmith.io/redpanda/connectors/connectors:624ff9e
    restart: unless-stopped
    hostname: connect
    container_name: connect
    ports:
      - "8083:8083"
    environment:
      KAFKA_CONNECT_CONFIGURATION: |
          offset.storage.topic=docker-connect-offsets
          value.converter=org.apache.kafka.connect.json.JsonConverter
          config.storage.topic=docker-connect-configs
          key.converter=org.apache.kafka.connect.json.JsonConverter
          group.id=compose-connect-group
          status.storage.topic=docker-connect-status
          config.storage.replication.factor=1
          offset.storage.replication.factor=1
          status.storage.replication.factor=1
      KAFKA_CONNECT_METRICS_ENABLED: "false"
      KAFKA_CONNECT_BOOTSTRAP_SERVERS: redpanda:9092
      KAFKA_GC_LOG_ENABLED: "false"
      KAFKA_HEAP_OPTS: -Xms128M
    depends_on:
      redpanda:
        condition: service_healthy
    profiles:
      - extra

  materialized:
    image: materialize/materialized:${MATERIALIZED_VERSION}
    container_name: ${MATERIALIZED_CONTAINER_NAME}
    depends_on:
      redpanda:
        condition: service_healthy
    restart: unless-stopped
    environment:
      # TODO: minio
      MZ_PERSIST_BLOB_URL: file:///tmp/blob.blob
    ports:
      - "${MATERIALIZED_PORT_DB_EXTERNAL}:${MATERIALIZED_PORT_DB_INTERNAL}"
      - "${MATERIALIZED_PORT_HTTP_EXTERNAL}:${MATERIALIZED_PORT_HTTP_INTERNAL}"
    healthcheck:
      test: "PGHOST=${MATERIALIZED_CONTAINER_NAME} PGPORT=${MATERIALIZED_PORT_DB_INTERNAL} PGDATABASE=${MATERIALIZED_DATABASE} PGUSER=${MATERIALIZED_USERNAME} PGPASSWORD=${MATERIALIZED_PASSWORD} pg_isready"
      interval: 5s
      start_period: 45s
    profiles:
      - materialized

  materialized-cli:
    image: materialize/cli:${MATERIALIZED_VERSION}
    restart: unless-stopped
    container_name: materialized-cli
    init: true
    tty: true
    stdin_open: true
    environment:
      PGHOST: ${MATERIALIZED_CONTAINER_NAME}
      PGPORT: ${MATERIALIZED_PORT_DB_INTERNAL}
      PGDATABASE: ${MATERIALIZED_DATABASE}
      PGUSER: ${POSTGRES_METABASE_USERNAME}
      PGPASSWORD: ${POSTGRES_METABASE_PASSWORD}
    depends_on:
      materialized:
        condition: service_healthy
      redpanda:
        condition: service_healthy
    profiles:
      - materialized

  dbt:
    image: ${DBT_IMAGE}:${DBT_VERSION}
    container_name: ${DBT_CONTAINER_NAME}
    restart: "no"
    stdin_open: true
    tty: true
    command: bash -c 'dbt run --project-dir=/usr/app; dbt docs generate --project-dir=/usr/app; dbt docs serve --project-dir=/usr/app'
    volumes:
      - ./etc/dbt/app/dbt/example:/usr/app/
      - ./etc/dbt/profile/:/root/.dbt/
    ports:
      - "${DBT_PORT_EXTERNAL}:${DBT_PORT_INTERNAL}"
    environment:
      DBT_PROFILES_DIR: /root/.dbt
      TZ: Etc/GMT+1
    depends_on:
      materialized:
        condition: service_healthy
    healthcheck: { test: "curl -f localhost:${DBT_PORT_INTERNAL}", interval: 1s, start_period: 30s }
    profiles:
      - dbt

  metabase-postgres:
    image: postgres:${POSTGRES_METABASE_VERSION}
    container_name: ${POSTGRES_METABASE_CONTAINER_NAME}
    restart: unless-stopped
    ports:
      - "${POSTGRES_METABASE_PORT_EXTERNAL}:${POSTGRES_METABASE_PORT_INTERNAL}"
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: ${POSTGRES_METABASE_DATABASE}
      POSTGRES_USER: ${POSTGRES_METABASE_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_METABASE_PASSWORD}
    volumes:
      - metabase-postgres:/var/lib/postgresql/data
    healthcheck: { test: "pg_isready", interval: 5s, start_period: 30s }
    profiles:
      - metabase

# https://github.com/osixia/docker-openldap/blob/master/example/docker-compose.yml
  openldap:
    image: bitnami/openldap:2.4.57
    container_name: openldap
    restart: unless-stopped
    ports:
      - 1389:1389
    environment:
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01@metabase.com,user02@metabase.com
      - LDAP_PASSWORDS=password1!,password2!
      - LDAP_PORT_NUMBER=1389
      - LDAP_ROOT=dc=example,dc=org
      - LDAP_USER_DC=users
      - LDAP_GROUP=readers
    # healthcheck: {test: " ldapsearch -H ldap://127.0.0.1:1389 -D dc=example,dc=com -w GoodNewsEveryone -b cn=admin,dc=planetexpress,dc=com", interval: 1s, start_period: 30s}
    profiles:
      - metabase

  metabase:
    image: metabase/metabase:${METABASE_VERSION}
    container_name: ${METABASE_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - "./etc/metabase/data:/metabase-data"
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: ${POSTGRES_METABASE_CONTAINER_NAME}
      MB_DB_PORT: ${POSTGRES_METABASE_PORT_INTERNAL}
      MB_DB_DBNAME: ${POSTGRES_METABASE_DATABASE}
      MB_DB_USER: ${POSTGRES_METABASE_USERNAME}
      MB_DB_PASS: ${POSTGRES_METABASE_PASSWORD}
      MB_LDAP_ENABLED: true
      MB_LDAP_BIND_DN: cn=admin,dc=example,dc=org
      MB_LDAP_GROUP_BASE: cn=readers
      MB_LDAP_HOST: openldap
      MB_LDAP_PASSWORD: adminpassword
      MB_LDAP_PORT: 1389
      MB_LDAP_USER_BASE: ou=users,dc=example,dc=org
      MB_LDAP_ATTRIBUTE_EMAIL: uid
      MB_LDAP_ATTRIBUTE_FIRSTNAME: uid
      MB_LDAP_ATTRIBUTE_LASTNAME: sn
    ports:
      - ${METABASE_PORT_EXTERNAL}:${METABASE_PORT_INTERNAL}
    depends_on:
      materialized:
        condition: service_healthy
      metabase-postgres:
        condition: service_healthy
      # openldap: { condition: }
    healthcheck: { test: "curl -f ${METABASE_CONTAINER_NAME}:${METABASE_PORT_INTERNAL}", interval: 1s, start_period: 30s }


volumes:
  redpanda:
  metabase-postgres:
