example:
  outputs:
    prod:
      type: materialize
      threads: 1
      host: materialized
      port: 6875
      user: materialize
      pass: materialize
      database: materialize
      schema: public
      cluster: default
      sslmode: require

    dev:
      type: materialize
      threads: 1
      host: materialized
      port: 6875
      user: materialize
      pass: materialize
      database: materialize
      schema: public
      cluster: default
      sslmode: require

    target: dev
